tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "dart-lang/dart"
tap "koekeishiya/formulae"

brew "yabai"
brew "skhd"
brew "fvm"
brew "bat"
brew "cocoapods"
brew "exa"
brew "gh"
brew "git"
brew "lazygit"
brew "neovim"
brew "pyenv"
brew "zoxide"
brew "fzf"
brew "tmux"
brew "tree"
brew "vim"
brew "zlib"
brew "fastlane"

cask "postman"
cask "iterm2"
cask "raycast"
cask "figma"
cask "visual-studio-code"
cask "android-studio"
cask "android-platform-tools"
cask "google-chrome"
cask "google-cloud-sdk"
cask "slack"

mas "Xcode", id: 497799835
