tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "wix/brew"

brew "asdf"
brew "applesimutils"
brew "bat"
brew "cocoapods"
brew "exa"
brew "gh"
brew "git"
brew "lazygit"
brew "neovim"
brew "zoxide"
brew "fzf"
brew "thefuck"
brew "tmux"
brew "tree"
brew "vim"
brew "zlib"
brew "fastlane"

cask "iterm2"
cask "raycast"
cask "rectangle"
cask "figma"
cask "visual-studio-code"
cask "android-studio"
cask "android-platform-tools"
cask "google-chrome"
cask "google-cloud-sdk"
cask "slack"

mas "Xcode", id: 497799835
